name: Install Salesforce CLI

on:
  push:
    branches:
      - main

jobs:
  install-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CLI
        run: npm install @salesforce/cli --global

      - name: Verify
        run: sf --version